name: Bob Samuelson
favicon: null
layout_spectrum: 0.6936256205663085
typography_spectrum: 0.1404096579644829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5328443411272019
  lightness: 0.08819268434308469
  saturation: 0.04177500889636576
  rhythmicContrast: 0.0166632782202214
purpose: []
